version: "3.8"

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "8000:8000"
    command: >
      gunicorn user-service.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./user-service:/app
      - ./user-service/staticfiles:/app/staticfiles
    environment:
      - DJANGO_SETTINGS_MODULE=user-service.settings

  product-service:
    build:
      context: ./product-service
    ports:
      - "8001:8000"
    command: >
      gunicorn product-service.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./product-service:/app
      - ./product-service/staticfiles:/app/staticfiles
    environment:
      - DJANGO_SETTINGS_MODULE=product-service.settings

  inventory-service:
    build:
      context: ./inventory-service
    ports:
      - "8002:8000"
    command: >
      gunicorn inventory-service.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./inventory-service:/app
      - ./inventory-service/staticfiles:/app/staticfiles
    environment:
      - DJANGO_SETTINGS_MODULE=inventory-service.settings

  order-service:
    build:
      context: ./order-service
    ports:
      - "8003:8000"
    command: >
      gunicorn order-service.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./order-service:/app
      - ./order-service/staticfiles:/app/staticfiles
    environment:
      - DJANGO_SETTINGS_MODULE=order-service.settings
